### ISSUE TITLE
Error: Failed to execute algorithm at 0x80000000: -4

### ISSUE THREAD

**Issue by Ocean276** [riscv-mcu/riscv-openocd#10]
the version of openocd that i used is nuclei 2023.10，after I built my own openocd，and I use it in nuclei studio, a mistake happend：
Info : Using libusb driver
Info : clock speed 1000 kHz
Info : JTAG tap: riscv.cpu tap/device found: 0x1e200a6d (mfg: 0x536 (Nuclei System Technology Co Ltd), part: 0xe200, ver: 0x1)
Info : [riscv.cpu] Found 0 triggers
halted at 0x2000028c due to debug interrupt
Info : Examined RISCV core; XLEN=32, misa=0x40001105
[riscv.cpu] Target successfully examined.
Info : starting gdb server for riscv.cpu on 3333
Info : Listening on port 3333 for gdb connections
Info : Valid NUSPI on device Nuclei SoC SPI Flash at address 0x20000000 with spictrl regbase at 0x10014000
Info : Nuclei SPI controller version 0x00000000
Info : Found flash device 'gd gd25q32c' (ID 0x001640c8)
cleared protection for sectors 0 through 63 on flash bank 0

Started by GNU MCU Eclipse
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : accepting 'gdb' connection on tcp/3333
Warn : Prefer GDB command "target extended-remote :3333" instead of "target remote :3333"
Info : JTAG tap: riscv.cpu tap/device found: 0x1e200a6d (mfg: 0x536 (Nuclei System Technology Co Ltd), part: 0xe200, ver: 0x1)
halted at 0x2000028c due to debug interrupt
Info : JTAG tap: riscv.cpu tap/device found: 0x1e200a6d (mfg: 0x536 (Nuclei System Technology Co Ltd), part: 0xe200, ver: 0x1)
halted at 0x2000028c due to debug interrupt
Info : Padding image section 0 at 0x200000ba with 2 bytes
Info : Padding image section 1 at 0x2000260e with 2 bytes
Error: TODO: debug_execution is true
Error: Failed to execute algorithm at 0x80000000: -4
Error: error writing to flash at address 0x20000000 at offset 0x00000000
halted at 0x2000028c due to debug interrupt
Info : JTAG tap: riscv.cpu tap/device found: 0x1e200a6d (mfg: 0x536 (Nuclei System Technology Co Ltd), part: 0xe200, ver: 0x1)
halted at 0x2000028c due to debug interrupt
halted at 0x2000028c due to debug interrupt
Info : dropped 'gdb' connection

I do not know if some wrong operations in the building process, hoping there are someone can help me, please.
my email is 202322230137@std.uestc.edu.cn, you can leave a message or contact me with email, thanks!

**Comment by fanghuaqi** [comment]
Need more details about your environment, your hardware ip, your hardware, any workable version?

Please at least find a workable version to prove this release has issue to be fixed.

**Comment by Ocean276** [comment]
Fine, I want to know the Nuclei OpenOCD 2022.12 is used by which version of the release, is nuclei-master or nuclei-develop? I mean maybe the differ of version cause that failed to execute algorithm, thanks for your reply.

**Comment by fanghuaqi** [comment]
You can get the git commit like this https://doc.nucleisys.com/nuclei_tools/openocd/intro.html#how-to-determine-the-version-of-openocd

For 2022.12, it should be https://github.com/riscv-mcu/riscv-openocd/tree/787e48e66

For 2023.10, it should be https://github.com/riscv-mcu/riscv-openocd/tree/af1da4806

**Comment by fanghuaqi** [comment]
For your case, I thought it maybe caused by this commit for `2023.10` release is missing https://github.com/riscv-mcu/riscv-openocd/commit/787e48e66c9980545fcf1363839779f8d32d3840, this is mainly for using opensource hbird processor which debugger spec is 0.11

**Comment by fanghuaqi** [comment]
Hi @Ocean276, are you using hbird or hbirdv2 processor?

**Comment by Ocean276** [comment]
Yes, I am using Hbirdv2 processor, and I am using a new flash that the openocd can not support, so I need to rebuild the openocd. While rebuilding openocd, I can not specify the 2022.12 but specify 787e48e is useless, so I choose nuclei-master instead, I don't know if that effect. What is missing 787e48e means? How can I do to fix that, 谢谢！

**Comment by Ocean276** [comment]
There is another question do you know? When debugging openocd, a parameter called work-area-size is used to adjust the size of the workspace. In the nuclei studio, the workspace can only be set to 0x1352 or less. Where can I set this value, and can it be smaller?

**Comment by fanghuaqi** [comment]
> Yes, I am using Hbirdv2 processor, and I am using a new flash that the openocd can not support, so I need to rebuild the openocd. While rebuilding openocd, I can not specify the 2022.12 but specify [787e48e](https://github.com/riscv-mcu/riscv-openocd/commit/787e48e66c9980545fcf1363839779f8d32d3840) is useless, so I choose nuclei-master instead, I don't know if that effect. What is missing [787e48e](https://github.com/riscv-mcu/riscv-openocd/commit/787e48e66c9980545fcf1363839779f8d32d3840) means? How can I do to fix that, 谢谢！

If you want to use the correct commit to build `2022.12`, please use commit 787e48e, which is on the branch  https://github.com/riscv-mcu/riscv-openocd/commits/nuclei-release, for the latest one commit it just added an extra flash supported.

**Comment by fanghuaqi** [comment]
> There is another question do you know? When debugging openocd, a parameter called work-area-size is used to adjust the size of the workspace. In the nuclei studio, the workspace can only be set to 0x1352 or less. Where can I set this value, and can it be smaller?

Please check `openocd/doc/pdf/openocd.pdf` for openocd user guide, the basic user guide can be found here https://doc.nucleisys.com/nuclei_tools/openocd/intro.html

**Comment by Ocean276** [comment]
After using the release version, the problem was solved, thank you very much!

**Comment by fanghuaqi** [comment]
If you are using `2023.10` release, you can checkout to `nuclei/2023.10` branch, and rebuild an openocd, it should be fixed for opensource hbird/hbirdv2 processor flash download.

@Ocean276 could you take a try with the latest `nuclei/2023.10` branch source code, and apply your local changes, and see whether this branch fix your issue.

**Comment by fanghuaqi** [comment]
@Ocean276 Could you take a try and give me feedback?

> If you are using `2023.10` release, you can checkout to `nuclei/2023.10` branch, and rebuild an openocd, it should be fixed for opensource hbird/hbirdv2 processor flash download.
> 
> @Ocean276 could you take a try with the latest `nuclei/2023.10` branch source code, and apply your local changes, and see whether this branch fix your issue.

**Comment by Ocean276** [comment]
After receiving your letter, I immediately recompiled the version of 2023.10, and it was successfully burned, really incredible, you repaired it in just a few days, awesome engineer, thank you again!

**Comment by fanghuaqi** [comment]
Okay, thanks for your confirmation. 

> After receiving your letter, I immediately recompiled the version of 2023.10, and it was successfully burned, really incredible, you repaired it in just a few days, awesome engineer, thank you again!
